Update CI files for branch main
pulp/pulp_file pull request #1071
Opened 2023-11-05 02:35 UTC by pulpbot

[noissue]

2023-11-13 07:35 UTC, mdellweg requested changes
Don't merge this. Please don't close it either.

2023-11-27 09:44 UTC, mdellweg requested changes

2023-11-27 09:44 UTC, mdellweg commented on .github/workflows/nightly.yml
> +    runs-on: "ubuntu-latest"
This line is wrong and will currently prevent the nightly to run.

2024-03-08 12:33 UTC, mdellweg approved these changes

2024-03-08 14:02 UTC, ggainey approved these changes

2024-03-08 14:04 UTC, merged