Outline the bugfix backport process
pulp/pulp_file pull request #1092
Opened 2023-11-29 09:59 UTC by mdellweg

[noissue]

2023-11-29 10:13 UTC, ipanova commented on README.rst
> +Any issues that asrise should also be solved there first and if needed backported to here. We do
s/asrise/arise

2023-11-29 10:14 UTC, ipanova commented on README.rst
> +Any issues that asrise should also be solved there first and if needed backported to here. We do
s/backported to here/backported here

2023-11-29 10:15 UTC, ipanova commented on README.rst
> +Any issues that asrise should also be solved there first and if needed backported to here. We do
I would drop last 3 sentences

2023-11-29 19:15 UTC, ggainey requested changes

2023-11-29 19:15 UTC, ggainey commented on README.rst
> +happens. Please excuse if this takes more time than estimated.
```suggestion
Any issues that arise should also be solved there first and if needed backported to here. We expect this to happen only infrequently, if ever. We will therefore  work out the details when / if it
happens. Please excuse us if this takes more time than desired.
```

2023-11-30 14:00 UTC, ggainey commented on README.rst
> +happens. Please excuse if this takes more time than estimated.
Dropping it sounds good, for exactly @ipanova 's reasoning

2023-12-01 11:48 UTC, ipanova approved these changes

2023-12-01 12:31 UTC, ggainey approved these changes

2023-12-01 12:32 UTC, merged