Fix distribution base url on docs tests
pulp/pulp_file pull request #505
Opened 2021-05-17 14:57 UTC by fao89

[noissue]

2021-05-17 15:51 UTC, dkliban approved these changes

2021-05-17 15:51 UTC, bmbouter commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
The new RQ==1.8.1 release is out which is compatible with click 8.0. https://pypi.org/project/rq/#history

Do we still need to restrict this?

2021-05-17 15:52 UTC, fao89 commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
yes, CI was breaking before
https://github.com/pulp/pulp_file/runs/2601995311?check_suite_focus=true#step:9:1397
it seems pulp-cli still incompatible with 8.0

2021-05-17 15:57 UTC, fao89 commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
I put it here on purpose, when applying CI template it will be removed, so it will be undone naturally.
I have no idea about pulp-cli release timeline

2021-05-17 16:29 UTC, mdellweg commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
I think, @daviddavis wants to release pulp-cli 0.9.0 with a pinned version of click today.

2021-05-17 17:34 UTC, daviddavis commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
Once this job is done, pulp-cli 0.9.0 should be on pypi: https://github.com/pulp/pulp-cli/actions/runs/850630787

2021-05-17 20:01 UTC, fao89 commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
It still breaking, because pulp-smash is forcing click 8.0.0
```
Attempting uninstall: click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
```
https://github.com/pulp/pulp_file/pull/505/checks?check_run_id=2604129145#step:5:247

2021-05-17 20:12 UTC, fao89 commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
probably not the best solution but I think this would fix:
https://github.com/pulp/pulp-smash/pull/1254

2021-05-18 08:04 UTC, mdellweg commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
FWIW: RQ, and the cli should not collide on dependencies, because rq is installed inside and the cli outside of the ci-container.
I do however see the cli and smash collide. There could be one way to separate them by installing the cli in a separate venv (maybe using pipx).

2021-05-18 19:50 UTC, fao89 commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
even switching pulp-cli and pulp-smash order doesn't fix the problem,
pulpcore `doc_requirements.txt` brings back click 8.0.0

https://github.com/pulp/pulp_file/runs/2613216940?check_suite_focus=true#step:6:55

2021-05-19 08:40 UTC, mdellweg approved these changes

2021-05-19 12:33 UTC, bmbouter commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
The pulpcore now does not have a click 8.0.0 requirements. @fao89 I think moving back the changes related to that should now work (as of about 2 hours ago) https://github.com/pulp/pulpcore/pull/1337/files

2021-05-19 12:34 UTC, bmbouter requested changes
I wanted to see if the click issue was resolved with no changes in this PR now that https://github.com/pulp/pulpcore/pull/1337/files is merged.

2021-05-19 12:36 UTC, mdellweg commented on .github/workflows/ci.yml
> +          pip install "click<8.0"
I'm trying to do away with the click 7 dependency in the cli here:
https://github.com/pulp/pulp-cli/pull/246

2021-05-19 13:02 UTC, fao89 commented
> I wanted to see if the click issue was resolved with no changes in this PR now that https://github.com/pulp/pulpcore/pull/1337/files is merged.



> I wanted to see if the click issue was resolved with no changes in this PR now that https://github.com/pulp/pulpcore/pull/1337/files is merged.

Look at the commit message, this PR only works because of that PR

2021-05-19 14:21 UTC, bmbouter commented
Mmmm I see, ty. Why is the cli block moving? I can also defer to the other reviewers happily, I'm just curious.

2021-05-19 14:24 UTC, fao89 commented
> Mmmm I see, ty. Why is the cli block moving? I can also defer to the other reviewers happily, I'm just curious.

because I thought pulp-smash needed to be installed first: https://github.com/pulp/plugin_template/pull/389

2021-05-19 14:41 UTC, bmbouter approved these changes

2021-05-19 14:44 UTC, merged