Rewrite unittest-based repository reclaim tests to pytest
pulp/pulp_file pull request #840
Opened 2022-10-05 14:12 UTC by lubosmj

Required PR: https://github.com/pulp/pulpcore/pull/3281

closes #821

2022-10-11 21:23 UTC, gerrod3 requested changes

2022-10-11 21:23 UTC, gerrod3 commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +        body["publication"] = publication.pulp_href
```suggestion
        body = gen_distribution(publication=publication.pulp_href)
```

2022-10-11 21:23 UTC, gerrod3 commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +    assert artifacts >= artifacts_before_download
```suggestion
    assert artifacts > artifacts_before_download
```
The original assertion was just greater than.

2022-10-11 21:23 UTC, gerrod3 commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +    assert artifacts >= artifacts_after_reclaim
```suggestion
    assert artifacts > artifacts_after_reclaim
```

2022-10-12 00:41 UTC, dkliban requested changes
I left some comments. I believe most of the tests can be run in parallel. I also suspect that you could possibly combine this workflow with the download policy tests[0]. 

[0] https://github.com/pulp/pulp_file/blob/main/pulp_file/tests/functional/api/test_download_policies.py

2022-10-12 00:41 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +def test_reclaim_immediate_content(
We should mark this test as parallel.

2022-10-12 00:41 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +    # assert no artifacts left
We should assert that the artifacts that were in the fixture repository are no longer in Pulp. Here is an example[0].

[0] https://github.com/pulp/pulp_file/blob/main/pulp_file/tests/functional/api/test_download_policies.py#L66-L67

2022-10-12 00:41 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +    # assert re-sync populated missing artifacts
We should that the specific artifacts are there. Similar to above.

2022-10-12 00:41 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +def test_immediate_reclaim_becomes_on_demand(
This test can also be marked as parallel.

2022-10-12 00:41 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_reclaim_disk_space.py
> +    download_content_unit(distribution.base_path, content["relative_path"])
You should switch from this fixture to the existing method in utils[0].

[0] https://github.com/pulp/pulp_file/blob/main/pulp_file/tests/functional/utils.py#L315-L323

2022-10-17 14:43 UTC, dkliban approved these changes

2022-10-17 14:57 UTC, gerrod3 approved these changes

2022-10-17 14:59 UTC, merged