Convert repo-versions tests to pytest
pulp/pulp_file pull request #850
Opened 2022-10-18 21:10 UTC by gerrod3

fixes: #823
Required PR: https://github.com/pulp/pulpcore/pull/3329

2022-10-18 21:18 UTC, gerrod3 commented
Testing results:

Test - Old timer, New timer
AddRemoveContentTestCase 12 - 8
SyncChangeRepoVersionTestCase 8 - removed, wasn't testing anything new
AddRemoveRepoVersionTestCase 28 - 13
test_squash_repo_version 13 - 13, didn't change this test
ContentImmutableRepoVersionTestCase 6 - 7
FilterRepoVersionTestCase 2:36 - 11 (This test had eight 10 second sleep statements before)
CreatedResourcesTaskTestCase 6 - 5
CreateRepoBaseVersionTestCase 27 - 10
UpdateRepoVersionTestCase 7 - merged into ContentImmutableRepoVersion
FilterArtifactsTestCase 23 - 8
DeleteRepoVersionResourcesTestCase 16 - 8
ClearAllUnitsRepoVersionTestCase 29 - 10
BaseVersionTestCase 8 - removed, wasn't really testing anything
RepoVersionRetentionTestCase 40 - 13
ContentInRepositoryVersionViewTestCase 8 - 6

Old total: 387 secs
New total: 120 secs
Roughly 3x faster, although all tests are now parallelized (these results are from serial running).

2022-10-20 19:05 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +    repo = gen_object_with_cleanup(file_repo_api_client, gen_repo())
why not use the `file_repo` fixture?

2022-10-20 19:34 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +    repo = gen_object_with_cleanup(file_repo_api_client, gen_repo())
Seems like you could use the `file_repo` fixture here also.

2022-10-20 19:36 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +    # Delete a repository version and filter by its number
Extra indentation here.

2022-10-20 19:37 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +def test_created_resources_task(
This test doesn't seem to be needed. We could make this assertion in any of the other tests.

2022-10-20 19:56 UTC, gerrod3 commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +    repo = gen_object_with_cleanup(file_repo_api_client, gen_repo())
You are right, I factored out shared code into the `file_populate_pulp` fixture and forgot to switch over to `file_repo`

2022-10-20 20:32 UTC, dkliban commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +    publication = gen_object_with_cleanup(file_pub_api_client, pub_body)
You could use a `file_repo_with_auto_publish` fixture for this part of the test. 

https://github.com/pulp/pulp_file/blob/main/pulp_file/tests/functional/api/test_auto_publish.py#L22

2022-10-20 20:34 UTC, dkliban requested changes
The required changes are with regard to broader use of `file_repo` fixture. I would like to also see the use of the `file_repo_with_auto_publish` where you need publications to be created. 

I believe we could combine most of these tests into one long test. However, it's up to you if you want to try to do that.

2022-10-21 01:41 UTC, gerrod3 commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +def test_created_resources_task(
Removed and placed assertion in the first test.

2022-10-21 01:43 UTC, gerrod3 commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +    # Delete a repository version and filter by its number
I'm confused, this seems correct to me. The delete is a separate part of the test, it is not apart of the for loop.

2022-10-21 01:45 UTC, gerrod3 commented on pulp_file/tests/functional/api/from_pulpcore/test_repo_versions.py
> +    publication = gen_object_with_cleanup(file_pub_api_client, pub_body)
I think using less complex features makes the test easier to understand and more confined to what we want to test.

2022-10-24 17:07 UTC, dkliban approved these changes

2022-10-26 12:15 UTC, merged