Rewrite export tests to pytest
pulp/pulp_file pull request #855
Opened 2022-10-27 13:48 UTC by mdellweg

fixes #818

2022-11-02 14:53 UTC, dkliban commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        if repositories is None:
Maybe just change the default to `[]`?

2022-11-02 14:58 UTC, mdellweg commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        if repositories is None:
Rule of python: Do not put mutable objects in function signatures!

2022-11-02 17:57 UTC, dralley commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        if repositories is None:
Indeed, it's a major footgun.

2022-11-02 19:56 UTC, dkliban commented on pulp_file/tests/functional/conftest.py
> +from pulp_smash.pulp3.bindings import monitor_task
I believe `pulpcore.tests` has `monitor_task` also.

2022-11-02 20:05 UTC, dkliban commented on pulp_file/tests/functional/conftest.py
> +# TODO rename the original fixture
Why do you want to change the name to `file_remote_factory` without actually renaming it?

2022-11-02 20:13 UTC, dkliban commented on pulp_file/tests/functional/api/test_pulp_export.py
> +    exporters = exporters_pulp_api_client.list().results
I tend to filter the results in list assertions. The test would fail if there were a lot of exporters and this one was not on the first page of the results. Seems improbably, but the test does run in parallel. Could possibly fail if run against a real system.

2022-11-02 20:33 UTC, dkliban requested changes
Some questions and suggested changes inline. Overall this looks amazing!

2022-11-02 20:40 UTC, dkliban commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        if repositories is None:
thanks for the explanation. i was not aware of this.

2022-11-03 08:59 UTC, mdellweg commented on pulp_file/tests/functional/conftest.py
> +from pulp_smash.pulp3.bindings import monitor_task
Too many `monitor_task` implementations around.
I intend to provide a fixture for it here: https://github.com/pulp/pulpcore/pull/3378
Can we just consolidate that later?

2022-11-03 09:00 UTC, mdellweg commented on pulp_file/tests/functional/conftest.py
> +# TODO rename the original fixture
I'm going to pull back on the renaming for this pr.

2022-11-03 09:21 UTC, mdellweg commented
Incorporated: https://github.com/pulp/pulp_file/pull/856

2022-11-03 12:46 UTC, dkliban commented on pulp_file/tests/functional/utils.py
> +    cli_client.run(cmd)
you don't need to use cli_client anymore. Just use `os.rmdir` to remove the directory.

2022-11-03 12:58 UTC, mdellweg commented on pulp_file/tests/functional/utils.py
> +    cli_client.run(cmd)
Yes!

2022-11-03 12:59 UTC, lubosmj commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        )
I am not sure if this will work for tests that do not contain the `pulp_cfg` fixture. A safer way for me is doing this: https://github.com/pulp/pulp_file/blob/6651e7988f37072688bb6445ceda230755d7770e/pulp_file/tests/functional/api/from_pulpcore/test_repair.py#L21-L27.

What do you think?

2022-11-03 12:59 UTC, lubosmj commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        file_content_api_client.create(
The response for such a request should be a task (https://docs.pulpproject.org/pulp_file/restapi.html#tag/Content:-Files/operation/content_file_files_create). Did you forget to call `monitor_task`?

2022-11-03 13:04 UTC, mdellweg commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        file_content_api_client.create(
Good catch!

2022-11-03 13:09 UTC, lubosmj commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        )
Is it possible to add the `allow_module_level=True` parameter to the `skip` method?

2022-11-03 15:08 UTC, mdellweg commented on pulp_file/tests/functional/api/test_pulp_export.py
> +        )
Changed to module level skip.

2022-11-03 15:16 UTC, dkliban approved these changes

2022-11-03 15:50 UTC, merged